
export const POST_AVATAR = "POST_AVATAR";
export const POST_AVATAR_SUCCESS = "POST_AVATAR_SUCCESS";
export const POST_AVATAR_FALSE = "POST_AVATAR_FALSE";

export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FALSE = "FETCH_ACCOUNT_FALSE";

export const POST_INFO = "POST_INFO";
