export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FALSE = "ADD_COMMENT_FALSE";

export const GET_LIST_COMMENT_POST = "GET_LIST_COMMENT_POST";
export const GET_LIST_COMMENT_POST_SUCCESS = "GET_LIST_COMMENT_POST_SUCCESS";
export const GET_LIST_COMMENT_POST_FALSE = "GET_LIST_COMMENT_POST_FALSE";
